# Generated by Django 5.0.7 on 2024-08-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='<--->', max_length=255, null=True),
        ),
    ]
